(async()=>{
const $=s=>document.querySelector(s),NS='http://www.w3.org/2000/svg',svg=$('#graph');const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const safe=s=>/^https?:\/\//i.test(s||'')?esc(s):'#';
let data,catalog,nodes=[],edges=[],byId=new Map(),selected=null,running=true,energy=1,pan={x:0,y:0,k:1},drag=null,frame,baseStats='';
const layer=document.createElementNS(NS,'g');svg.append(layer);
function transform(){layer.setAttribute('transform',`translate(${pan.x} ${pan.y}) scale(${pan.k})`)}
function zoom(f){const k=Math.max(.25,Math.min(4,pan.k*f));pan.x=450-(450-pan.x)*k/pan.k;pan.y=310-(310-pan.y)*k/pan.k;pan.k=k;transform()}
function point(e){const r=svg.getBoundingClientRect(),scale=Math.min(r.width/900,r.height/620),ox=(r.width-900*scale)/2,oy=(r.height-620*scale)/2;return{x:(e.clientX-r.left-ox)/scale,y:(e.clientY-r.top-oy)/scale}}
function reset(){pan={x:0,y:0,k:1};transform();selected=null;highlight();energy=1;running=true;$('#pause-graph').textContent='暂停布局';schedule()}
function activePapers(){const t=$('#network-topic').value;return new Set(Object.values(data.papers).filter(p=>t==='all'||p.topics.includes(t)).map(p=>p.id))}
function build(){
 const allowed=activePapers();nodes=data.nodes.filter(n=>n.papers.filter(id=>allowed.has(id)).length>=Number($('#min-papers').value)).map((n,i,a)=>({...n,papers:n.papers.filter(id=>allowed.has(id)),x:450+220*Math.cos(i*2.39996)*Math.sqrt((i+1)/a.length),y:310+220*Math.sin(i*2.39996)*Math.sqrt((i+1)/a.length),vx:0,vy:0}));byId=new Map(nodes.map(n=>[n.id,n]));edges=data.edges.filter(e=>byId.has(e.source)&&byId.has(e.target)&&e.papers.some(id=>allowed.has(id))).map(e=>({...e,papers:e.papers.filter(id=>allowed.has(id))}));layer.replaceChildren();
 for(const e of edges){e.el=document.createElementNS(NS,'line');e.el.classList.add('graph-edge');e.el.setAttribute('stroke-width',String(Math.min(4,.5+Math.sqrt(e.papers.length)*.5)));layer.append(e.el)}
 const ranked=[...nodes].sort((a,b)=>b.papers.length-a.papers.length).slice(0,12).map(n=>n.id);
 for(const n of nodes){const g=document.createElementNS(NS,'g');g.classList.add('graph-node');g.setAttribute('tabindex','0');g.setAttribute('role','button');g.setAttribute('aria-label',n.label+'，'+n.papers.length+' 篇文献');g.dataset.id=n.id;const c=document.createElementNS(NS,'circle');c.setAttribute('r',String(Math.min(15,4+Math.sqrt(n.papers.length)*2)));g.append(c);const label=document.createElementNS(NS,'text');label.setAttribute('x','12');label.setAttribute('y','4');label.textContent=n.label.length>34?n.label.slice(0,33)+'…':n.label;label.style.display=ranked.includes(n.id)?'':'none';g.append(label);const tip=document.createElementNS(NS,'title');tip.textContent=n.label;g.append(tip);n.el=g;n.labelEl=label;n.top=ranked.includes(n.id);g.addEventListener('click',()=>select(n.id));g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(n.id)}});g.addEventListener('pointerenter',()=>label.style.display='');g.addEventListener('pointerleave',()=>{if(!n.top&&n.id!==selected)label.style.display='none'});layer.append(g)}
 $('#institution-select').innerHTML='<option value="">选择机构…</option>'+[...nodes].sort((a,b)=>a.label.localeCompare(b.label)).map(n=>`<option value="${n.id}">${esc(n.label)} (${n.papers.length})</option>`).join('');
 $('#graph-stats').textContent=`${nodes.length} 个署名单位 · ${edges.length} 条联系 · ${new Set(nodes.flatMap(n=>n.papers)).size} 篇文献 · 全库另有 ${data.omitted_papers} 篇相关候选缺少可解析机构`;
 baseStats=$('#graph-stats').textContent;$('#graph-detail').innerHTML='<h2>选择一个机构</h2><p>查看它在当前文献中的作者、共同署名机构和论文。</p>';selected=null;reset();search();draw();
}
function select(id){$('#institution-search').value='';$('#graph-stats').textContent=baseStats;selected=id;$('#institution-select').value=id;const n=byId.get(id);if(!n)return;const allowed=new Set(n.papers),authors=n.authors.filter(a=>a.papers.some(p=>allowed.has(p))),links=edges.filter(e=>e.source===id||e.target===id).sort((a,b)=>b.papers.length-a.papers.length);$('#graph-detail').innerHTML=`<h2>${esc(n.label)}</h2><p>${n.papers.length} 篇已收录文献 · ${links.length} 个共同署名单位</p><h3>文献中的作者</h3>${authors.length?'<ul>'+authors.map(a=>`<li>${esc(a.name)} <small>(${a.papers.filter(p=>allowed.has(p)).length})</small></li>`).join('')+'</ul>':'<p>没有获取到明确的作者对应关系。</p>'}<h3>共同署名单位</h3>${links.length?'<ul>'+links.slice(0,30).map(e=>{const other=byId.get(e.source===id?e.target:e.source);return `<li><button class="institution-link" data-node="${other.id}">${esc(other.label)}</button> <small>${e.papers.length} 篇</small></li>`}).join('')+'</ul>':'<p>当前文献中没有其他共同署名单位。</p>'}<h3>相关文献</h3><ul>${n.papers.map(id=>{const p=data.papers[id];return `<li><a href="${safe(p.url)}" target="_blank" rel="noopener">${esc(p.title)} ↗</a><br><small>${esc(p.publication_date||'发布日期待核实')}</small></li>`}).join('')}</ul><details><summary>原始机构表述</summary><ul>${n.raw.map(r=>`<li>${esc(r)}</li>`).join('')}</ul></details><p><small>以上反映论文署名，不是当前任职名录。</small></p>`;highlight();}
$('#graph-detail').addEventListener('click',e=>{const b=e.target.closest('[data-node]');if(b)select(b.dataset.node)});
function highlight(){const neighbors=new Set([selected,...edges.filter(e=>e.source===selected||e.target===selected).flatMap(e=>[e.source,e.target])]);for(const n of nodes){n.el.classList.toggle('selected',n.id===selected);n.el.classList.toggle('dim',!!selected&&!neighbors.has(n.id));n.labelEl.style.display=n.top||n.id===selected?'':'none'}for(const e of edges){const on=e.source===selected||e.target===selected;e.el.classList.toggle('selected',on);e.el.classList.toggle('dim',!!selected&&!on)}}
function search(){const q=$('#institution-search').value.trim().toLowerCase();if(!q){$('#graph-stats').textContent=baseStats;highlight();return}selected=null;const ids=new Set(nodes.filter(n=>[n.label,...n.raw,...n.authors.map(a=>a.name)].join(' ').toLowerCase().includes(q)).map(n=>n.id));for(const n of nodes){n.el.classList.toggle('dim',!ids.has(n.id));n.el.classList.toggle('selected',ids.has(n.id));n.labelEl.style.display=ids.has(n.id)?'':'none'}for(const e of edges)e.el.classList.toggle('dim',!ids.has(e.source)&&!ids.has(e.target));$('#graph-stats').textContent=`找到 ${ids.size} 个匹配机构 · 点击节点或使用机构列表查看详情`;}
function draw(){for(const n of nodes)n.el.setAttribute('transform',`translate(${n.x} ${n.y})`);for(const e of edges){const a=byId.get(e.source),b=byId.get(e.target);for(const [key,v] of [['x1',a.x],['y1',a.y],['x2',b.x],['y2',b.y]])e.el.setAttribute(key,String(v))}}
function tick(){frame=null;if(!running||document.hidden)return;energy*=.96;for(let i=0;i<nodes.length;i++){const a=nodes[i];for(let j=i+1;j<nodes.length;j++){const b=nodes[j],dx=a.x-b.x||.01,dy=a.y-b.y||.01,d=Math.max(36,dx*dx+dy*dy),f=140*energy/d;a.vx+=dx*f;a.vy+=dy*f;b.vx-=dx*f;b.vy-=dy*f}a.vx+=(450-a.x)*.001*energy;a.vy+=(310-a.y)*.001*energy}for(const e of edges){const a=byId.get(e.source),b=byId.get(e.target),dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,f=(d-85)*.0025*energy;a.vx+=dx/d*f;a.vy+=dy/d*f;b.vx-=dx/d*f;b.vy-=dy/d*f}for(const n of nodes){n.vx*=.65;n.vy*=.65;if(drag?.id!==n.id){n.x=Math.max(24,Math.min(876,n.x+n.vx));n.y=Math.max(24,Math.min(596,n.y+n.vy))}}draw();if(energy>.015)schedule()}
function schedule(){if(!frame&&running)frame=requestAnimationFrame(tick)}
svg.addEventListener('pointerdown',e=>{const n=e.target.closest('.graph-node'),p=point(e);drag={id:n?.dataset.id,start:p,pan:{...pan},moved:false};svg.setPointerCapture(e.pointerId);if(n){energy=.3;schedule()}});
svg.addEventListener('pointermove',e=>{if(!drag)return;const p=point(e);if(drag.id){const n=byId.get(drag.id);n.x=(p.x-pan.x)/pan.k;n.y=(p.y-pan.y)/pan.k;n.vx=0;n.vy=0;draw()}else{pan.x=drag.pan.x+p.x-drag.start.x;pan.y=drag.pan.y+p.y-drag.start.y;transform()}drag.moved=true});svg.addEventListener('pointerup',e=>{if(drag?.id&&!drag.moved)select(drag.id);drag=null;if(svg.hasPointerCapture(e.pointerId))svg.releasePointerCapture(e.pointerId)});svg.addEventListener('pointercancel',()=>drag=null);svg.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY<0?1.1:.9)},{passive:false});
$('#zoom-in').onclick=()=>zoom(1.2);$('#zoom-out').onclick=()=>zoom(1/1.2);$('#reset-graph').onclick=()=>{$('#institution-search').value='';build()};$('#pause-graph').onclick=()=>{running=!running;$('#pause-graph').textContent=running?'暂停布局':'继续布局';if(running){energy=.25;schedule()}};$('#institution-select').onchange=e=>{if(e.target.value)select(e.target.value)};$('#institution-search').oninput=search;$('#network-topic').onchange=build;$('#min-papers').onchange=build;document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule()});
try{const results=await Promise.all([fetch('./network.json'),fetch('./catalog.json')]);if(results.some(r=>!r.ok))throw Error();[data,catalog]=await Promise.all(results.map(r=>r.json()));for(const t of catalog.topics){const o=document.createElement('option');o.value=t.id;o.textContent=t.name;$('#network-topic').append(o)}build()}catch(e){$('#graph-stats').textContent='机构网络数据暂时无法读取，请稍后刷新。'}
})();
