(async()=>{
const $=s=>document.querySelector(s),NS='http://www.w3.org/2000/svg',svg=$('#graph');const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const safe=s=>/^https?:\/\//i.test(s||'')?esc(s):'#';
let data,catalog,nodes=[],edges=[],byId=new Map(),selected=null,running=true,energy=1,pan={x:0,y:0,k:1},drag=null,frame,baseStats='',detailPapers=null,researcherId='';
const layer=document.createElementNS(NS,'g');svg.append(layer);
const displayName=n=>n.name_zh?`${n.name_zh} · ${n.label}`:n.label;
const personLabel=a=>a.name_zh?`${a.name_zh} · ${a.name}`:a.name;
const personMap=new Map();
function researcherOptions(){
 const q=$('#researcher-search').value.trim().toLowerCase(),topic=$('#network-topic').value;
 const people=[...personMap.values()].filter(a=>a.papers.some(id=>topic==='all'||data.papers[id]?.topics?.includes(topic))&&(!q||[a.name,a.name_zh,a.orcid,...(a.aliases||[])].join(' ').toLowerCase().includes(q))).sort((a,b)=>personLabel(a).localeCompare(personLabel(b),'zh-CN'));
 const labels=a=>{const orgs=a.institutions.map(id=>data.nodes.find(n=>n.id===id)).filter(Boolean).map(n=>n.name_zh||n.label);return `${personLabel(a)} — ${orgs.slice(0,2).join('、')||'机构待核实'} (${a.papers.length} 篇)`};
 $('#researcher-select').innerHTML='<option value="">选择研究者…</option>'+people.slice(0,80).map(a=>`<option value="${a.id}">${esc(labels(a))}</option>`).join('');
 if(researcherId&&!people.slice(0,80).some(a=>a.id===researcherId)){const a=personMap.get(researcherId);$('#researcher-select').insertAdjacentHTML('beforeend',`<option value="${a.id}">${esc(labels(a))}</option>`)}
 $('#researcher-select').value=researcherId;$('#researcher-count').textContent=`${people.length} 条匹配署名${people.length>80?' · 列表显示前 80 条，请输入姓名缩小范围':''}`;
}
function chooseResearcher(id){researcherId=id;$('#institution-search').value='';build()}
function researcherDetail(){
 const a=personMap.get(researcherId);if(!a)return;
 const allowed=activePapers(),paperIds=a.papers.filter(id=>allowed.has(id));
 const institutionIds=a.institutions.filter(id=>data.nodes.find(n=>n.id===id)?.authors.some(person=>person.id===a.id&&person.papers.some(p=>allowed.has(p))));
 $('#graph-detail').innerHTML=`<h2>${esc(personLabel(a))}</h2><p>${paperIds.length} 篇相关文献 · ${institutionIds.length} 个明确署名机构</p>${a.orcid?`<p><a href="${safe(a.orcid)}" target="_blank" rel="noopener">ORCID ↗</a></p>`:''}${a.name_source&&a.name_source!==a.orcid?`<p><a href="${safe(a.name_source)}" target="_blank" rel="noopener">姓名来源 ↗</a></p>`:''}<h3>论文署名机构</h3>${institutionIds.length?'<ul>'+institutionIds.map(id=>{const n=data.nodes.find(n=>n.id===id);return `<li>${byId.has(id)?`<button class="institution-link" data-node="${id}">${esc(displayName(n))}</button>`:esc(displayName(n))}</li>`}).join('')+'</ul>':'<p>当前未取得可核验的作者—机构对应关系。</p>'}<h3>相关文献</h3>${paperIds.length?'<ul>'+paperIds.map(id=>{const p=data.papers[id];return `<li><a href="${safe(p.url)}" target="_blank" rel="noopener">${esc(p.title)} ↗</a><br><small>${esc(p.publication_date||'发布日期待核实')}</small></li>`}).join('')+'</ul>':'<p>该研究者在当前研究方向下暂无文献，可切换“全部研究方向”。</p>'}<p><small>网络展示这些论文的机构共同署名，不代表个人关系或当前任职。${['name_and_institution','paper_signature'].includes(a.identity_basis)?'此项为姓名与署名范围相同的记录，未通过唯一标识确认跨机构身份。':''}</small></p>`;
}
function transform(){layer.setAttribute('transform',`translate(${pan.x} ${pan.y}) scale(${pan.k})`)}
function zoom(f){const k=Math.max(.25,Math.min(4,pan.k*f));pan.x=450-(450-pan.x)*k/pan.k;pan.y=310-(310-pan.y)*k/pan.k;pan.k=k;transform()}
function point(e){const r=svg.getBoundingClientRect(),scale=Math.min(r.width/900,r.height/620),ox=(r.width-900*scale)/2,oy=(r.height-620*scale)/2;return{x:(e.clientX-r.left-ox)/scale,y:(e.clientY-r.top-oy)/scale}}
function reset(){pan={x:0,y:0,k:1};transform();selected=null;detailPapers=null;highlight();energy=1;running=true;$('#pause-graph').textContent='暂停布局';schedule()}
function activePapers(){const t=$('#network-topic').value;return new Set(Object.values(data.papers).filter(p=>(t==='all'||p.topics.includes(t))&&(!researcherId||personMap.get(researcherId)?.papers.includes(p.id))).map(p=>p.id))}
function build(){
 const allowed=activePapers(), overview=$('#min-papers').value==='overview';let visible=data.nodes.map(n=>({...n,papers:n.papers.filter(id=>allowed.has(id))})).filter(n=>n.papers.length>=(researcherId?1:overview?2:Number($('#min-papers').value))).sort((a,b)=>(researcherId?Number(personMap.get(researcherId).institutions.includes(b.id))-Number(personMap.get(researcherId).institutions.includes(a.id)):0)||b.papers.length-a.papers.length||a.label.localeCompare(b.label));if(overview)visible=visible.slice(0,30);nodes=visible.map((n,i,a)=>({...n,papers:n.papers.filter(id=>allowed.has(id)),x:450+220*Math.cos(i*2.39996)*Math.sqrt((i+1)/a.length),y:310+220*Math.sin(i*2.39996)*Math.sqrt((i+1)/a.length),vx:0,vy:0}));byId=new Map(nodes.map(n=>[n.id,n]));edges=data.edges.filter(e=>byId.has(e.source)&&byId.has(e.target)&&e.papers.some(id=>allowed.has(id))).map(e=>({...e,papers:e.papers.filter(id=>allowed.has(id))}));// A maximum spanning forest preserves each component while removing dense cycles.
 const parent=new Map(nodes.map(n=>[n.id,n.id]));const root=id=>{while(parent.get(id)!==id)id=parent.get(id);return id};
 for(const e of [...edges].sort((a,b)=>b.papers.length-a.papers.length)){const a=root(e.source),b=root(e.target);e.primary=!overview||a!==b;if(a!==b)parent.set(a,b)}
 layer.replaceChildren();
 for(const e of edges){e.el=document.createElementNS(NS,'line');e.el.classList.add('graph-edge');e.el.setAttribute('stroke-width',String(Math.min(4,.5+Math.sqrt(e.papers.length)*.5)));layer.append(e.el)}
 const ranked=[...nodes].sort((a,b)=>b.papers.length-a.papers.length).slice(0,6).map(n=>n.id);
 for(const n of nodes){const g=document.createElementNS(NS,'g');g.classList.add('graph-node');g.setAttribute('tabindex','0');g.setAttribute('role','button');g.setAttribute('aria-label',displayName(n)+'，'+n.papers.length+' 篇文献');g.dataset.id=n.id;const c=document.createElementNS(NS,'circle');c.setAttribute('r',String(Math.min(15,4+Math.sqrt(n.papers.length)*2)));g.append(c);const label=document.createElementNS(NS,'text');label.setAttribute('x','12');label.setAttribute('y','4');const visibleLabel=n.name_zh||n.label;label.textContent=visibleLabel.length>28?visibleLabel.slice(0,27)+'…':visibleLabel;label.style.display=ranked.includes(n.id)?'':'none';g.append(label);const tip=document.createElementNS(NS,'title');tip.textContent=displayName(n);g.append(tip);n.el=g;n.labelEl=label;n.top=ranked.includes(n.id);g.addEventListener('click',()=>select(n.id));g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(n.id)}});g.addEventListener('pointerenter',()=>label.style.display='');g.addEventListener('pointerleave',()=>{if(!n.top&&n.id!==selected)label.style.display='none'});layer.append(g)}
 $('#institution-select').innerHTML='<option value="">选择机构…</option>'+[...nodes].sort((a,b)=>displayName(a).localeCompare(displayName(b),'zh-CN')).map(n=>`<option value="${n.id}">${esc(displayName(n))} (${n.papers.length})</option>`).join('');
 $('#graph-stats').textContent=`${nodes.length} 个一级机构 · ${edges.filter(e=>e.primary).length} 条主要联系 / ${edges.length} 条可见机构间联系 · ${new Set(nodes.flatMap(n=>n.papers)).size} 篇文献 · 全库另有 ${data.omitted_papers} 篇相关候选缺少已核验的一级机构`;
 baseStats=$('#graph-stats').textContent;$('#graph-detail').innerHTML='<h2>选择一个机构</h2><p>查看它在当前文献中的作者、共同署名机构和论文。</p>';selected=null;reset();search();draw();researcherOptions();$('#clear-researcher').hidden=!researcherId;$('#min-papers').disabled=!!researcherId;if(researcherId)researcherDetail();
}
function select(id,unitId=''){
 $('#institution-search').value='';$('#graph-stats').textContent=baseStats;selected=id;$('#institution-select').value=id;
 const n=byId.get(id);if(!n)return;
 const units=(n.units||[]).filter(u=>u.papers.some(p=>n.papers.includes(p))),unit=units.find(u=>u.id===unitId);
 const paperIds=unit?n.papers.filter(p=>unit.papers.includes(p)):n.papers,allowed=new Set(paperIds);
 detailPapers=allowed;
 const authors=n.authors.filter(a=>(unit?(a.unit_papers?.[unit.id]||[]):a.papers).some(p=>allowed.has(p)));
 // Detail counts include all partners, even those hidden by the overview cap.
 const links=data.edges.filter(e=>(e.source===id||e.target===id)&&e.papers.some(p=>allowed.has(p))).map(e=>({...e,papers:e.papers.filter(p=>allowed.has(p))})).sort((a,b)=>b.papers.length-a.papers.length);
 const personLabel=a=>a.name_zh?`${a.name_zh} · ${a.name}`:a.name;
 const authorName=a=>a.orcid&&/^https:\/\/orcid\.org\/\d{4}-\d{4}-\d{4}-\d{3}[\dX]$/.test(a.orcid)?`<button class="institution-link" data-researcher="${a.id}">${esc(personLabel(a))}</button> <a href="${a.orcid}" target="_blank" rel="noopener" aria-label="${esc(a.name)} 的 ORCID">ORCID ↗</a>`:`<button class="institution-link" data-researcher="${a.id}">${esc(personLabel(a))}</button>`;
 $('#graph-detail').innerHTML=`<h2>${esc(displayName(n))}</h2><p><small>名称已核验 · <a href="${safe(n.verification?.ror)}" target="_blank" rel="noopener">ROR 机构名录 ↗</a>${n.verification?.website?` · <a href="${safe(n.verification.website)}" target="_blank" rel="noopener">机构官网 ↗</a>`:''}</small></p><label>下属院系与研究单位 <select id="unit-select" aria-label="选择二级机构"><option value="">全部院系与单位 (${n.papers.length})</option>${units.map(u=>`<option value="${u.id}" ${unitId===u.id?'selected':''}>${esc(displayName(u))} (${u.papers.filter(p=>n.papers.includes(p)).length})</option>`).join('')}</select></label>${unit?`<p><small><a href="${safe(unit.source)}" target="_blank" rel="noopener">二级机构名称与归属核验来源 ↗</a></small></p>`:''}${units.length?'':'<p><small>暂无已核验的下属单位信息。</small></p>'}<p>${paperIds.length} 篇已收录文献 · ${links.length} 个共同署名一级机构</p><h3>文献中的作者</h3>${authors.length?'<ul>'+authors.map(a=>`<li>${authorName(a)}${a.name_zh&&a.name_source&&a.name_source!==a.orcid?` <a href="${safe(a.name_source)}" target="_blank" rel="noopener"><small>姓名来源 ↗</small></a>`:''} <small>(${(unit?(a.unit_papers?.[unit.id]||[]):a.papers).filter(p=>allowed.has(p)).length})</small></li>`).join('')+'</ul>':'<p>没有获取到明确的作者对应关系。</p>'}<h3>共同署名一级机构</h3>${links.length?'<ul>'+links.slice(0,30).map(e=>{const other=data.nodes.find(n=>n.id===(e.source===id?e.target:e.source));return `<li>${byId.has(other.id)?`<button class="institution-link" data-node="${other.id}">${esc(displayName(other))}</button>`:esc(displayName(other))} <small>${e.papers.length} 篇</small></li>`}).join('')+'</ul>':'<p>当前文献中没有其他共同署名一级机构。</p>'}<h3>相关文献</h3><ul>${paperIds.map(id=>{const p=data.papers[id];return `<li><a href="${safe(p.url)}" target="_blank" rel="noopener">${esc(p.title)} ↗</a><br><small>${esc(p.publication_date||'发布日期待核实')}</small></li>`}).join('')}</ul><p><small>院系、作者与 ORCID 来自论文署名或出版社元数据；未确认的字段不展示。以上不是当前任职名录。</small></p>`;
 $('#unit-select').onchange=e=>select(id,e.target.value);highlight();
}
$('#graph-detail').addEventListener('click',e=>{const b=e.target.closest('[data-node]');if(b)select(b.dataset.node);const person=e.target.closest('[data-researcher]');if(person)chooseResearcher(person.dataset.researcher)});
function highlight(){const relevant=e=>!detailPapers||e.papers.some(p=>detailPapers.has(p));const neighbors=new Set([selected,...edges.filter(e=>relevant(e)&&(e.source===selected||e.target===selected)).flatMap(e=>[e.source,e.target])]);for(const n of nodes){n.el.classList.toggle('selected',n.id===selected);n.el.classList.toggle('dim',!!selected&&!neighbors.has(n.id));n.labelEl.style.display=n.top||n.id===selected?'':'none'}for(const e of edges){const on=relevant(e)&&(e.source===selected||e.target===selected);e.el.style.display=(selected?on:e.primary)?'':'none';e.el.classList.toggle('selected',on);e.el.classList.toggle('dim',!!selected&&!on)}}
function search(){const q=$('#institution-search').value.trim().toLowerCase();if(!q){$('#graph-stats').textContent=baseStats;highlight();return}selected=null;const ids=new Set(nodes.filter(n=>[displayName(n),...n.raw,...(n.units||[]).map(displayName),...n.authors.map(a=>[a.name,a.name_zh].filter(Boolean).join(' '))].join(' ').toLowerCase().includes(q)).map(n=>n.id));for(const n of nodes){n.el.classList.toggle('dim',!ids.has(n.id));n.el.classList.toggle('selected',ids.has(n.id));n.labelEl.style.display=ids.has(n.id)?'':'none'}for(const e of edges){e.el.style.display=ids.has(e.source)||ids.has(e.target)?'':'none';e.el.classList.toggle('dim',!ids.has(e.source)&&!ids.has(e.target));}$('#graph-stats').textContent=`找到 ${ids.size} 个匹配机构 · 点击节点或使用机构列表查看详情`;}
function draw(){for(const n of nodes){n.el.setAttribute('transform',`translate(${n.x} ${n.y})`);n.labelEl.setAttribute('x',n.x<450?'-12':'12');n.labelEl.setAttribute('text-anchor',n.x<450?'end':'start');}for(const e of edges){const a=byId.get(e.source),b=byId.get(e.target);for(const [key,v] of [['x1',a.x],['y1',a.y],['x2',b.x],['y2',b.y]])e.el.setAttribute(key,String(v))}}
function tick(){frame=null;if(!running||document.hidden)return;energy*=.96;for(let i=0;i<nodes.length;i++){const a=nodes[i];for(let j=i+1;j<nodes.length;j++){const b=nodes[j],dx=a.x-b.x||.01,dy=a.y-b.y||.01,d=Math.max(36,dx*dx+dy*dy),f=(45/Math.max(1,nodes.length/30))*energy/d;a.vx+=dx*f;a.vy+=dy*f;b.vx-=dx*f;b.vy-=dy*f}a.vx+=(450-a.x)*.018*energy;a.vy+=(310-a.y)*.018*energy}for(const e of edges){const a=byId.get(e.source),b=byId.get(e.target),dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,f=(d-115)*.009*energy;a.vx+=dx/d*f;a.vy+=dy/d*f;b.vx-=dx/d*f;b.vy-=dy/d*f}for(const n of nodes){n.vx*=.65;n.vy*=.65;if(drag?.id!==n.id){n.x=Math.max(110,Math.min(790,n.x+n.vx));n.y=Math.max(90,Math.min(530,n.y+n.vy))}}draw();if(energy>.015)schedule()}
function schedule(){if(!frame&&running)frame=requestAnimationFrame(tick)}
svg.addEventListener('pointerdown',e=>{const n=e.target.closest('.graph-node'),p=point(e);drag={id:n?.dataset.id,start:p,pan:{...pan},moved:false};svg.setPointerCapture(e.pointerId);if(n){energy=.3;schedule()}});
svg.addEventListener('pointermove',e=>{if(!drag)return;const p=point(e);if(drag.id){const n=byId.get(drag.id);n.x=(p.x-pan.x)/pan.k;n.y=(p.y-pan.y)/pan.k;n.vx=0;n.vy=0;draw()}else{pan.x=drag.pan.x+p.x-drag.start.x;pan.y=drag.pan.y+p.y-drag.start.y;transform()}drag.moved=true});svg.addEventListener('pointerup',e=>{if(drag?.id&&!drag.moved)select(drag.id);drag=null;if(svg.hasPointerCapture(e.pointerId))svg.releasePointerCapture(e.pointerId)});svg.addEventListener('pointercancel',()=>drag=null);svg.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY<0?1.1:.9)},{passive:false});
$('#zoom-in').onclick=()=>zoom(1.2);$('#zoom-out').onclick=()=>zoom(1/1.2);$('#reset-graph').onclick=()=>{$('#institution-search').value='';$('#researcher-search').value='';researcherId='';build()};$('#pause-graph').onclick=()=>{running=!running;$('#pause-graph').textContent=running?'暂停布局':'继续布局';if(running){energy=.25;schedule()}};$('#institution-select').onchange=e=>{if(e.target.value)select(e.target.value)};$('#institution-search').oninput=search;$('#network-topic').onchange=build;$('#min-papers').onchange=build;document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule()});
$('#researcher-search').oninput=researcherOptions;$('#researcher-select').onchange=e=>chooseResearcher(e.target.value);$('#clear-researcher').onclick=()=>chooseResearcher('');
try{const results=await Promise.all([fetch('./network.json'),fetch('./catalog.json')]);if(results.some(r=>!r.ok))throw Error();[data,catalog]=await Promise.all(results.map(r=>r.json()));for(const a of data.researchers||[])personMap.set(a.id,a);for(const t of catalog.topics){const o=document.createElement('option');o.value=t.id;o.textContent=t.name+' · '+t.name_en;$('#network-topic').append(o)}build()}catch(e){$('#graph-stats').textContent='机构网络数据暂时无法读取，请稍后刷新。'}
})();
